<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PlatformTarget>AnyCPU</PlatformTarget>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="ReportItemSchemas.xsd" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="ReportItemSchemas.xsd" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SqlServer.Types" Version="160.1000.6" />
    <PackageReference Include="QuestPDF" Version="2025.7.0" />
  </ItemGroup>

</Project>
