<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" id="ReportItemSchemas" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="CustomerReportItem" nillable="true" type="CustomerReportItem" />
  <xs:complexType name="CustomerReportItem">
    <xs:sequence>
      <xs:element minOccurs="0" maxOccurs="1" name="Name" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="FirstName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="LastName" type="xs:string" />
      <xs:element minOccurs="0" maxOccurs="1" name="Department" type="xs:string" />
      <xs:element minOccurs="1" maxOccurs="1" name="Salary" type="xs:decimal" />
    </xs:sequence>
  </xs:complexType>
</xs:schema>